sonar.projectKey=mern-devsecops
sonar.projectName=MERN DevSecOps

sonar.sources=server,src

sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,build/**,public/**

# 🔥 THIS LINE ADD KAR
sonar.host.url=http://host.docker.internal:9000